#!/usr/bin/env python3

import re
import sys
from urllib import request

import browser_cookie3
from lxml import html


EX_USAGE = 64


if len(sys.argv) < 2:
    print('error: missing regex argument', file=sys.stderr)
    sys.exit(EX_USAGE)

regex = sys.argv[1]


url = 'https://chrome.google.com/webstore/devconsole/<UUID>'

cookie_jar = browser_cookie3.chrome(
    cookie_file='<profile-cookie-file>',
)

opener = request.build_opener(request.HTTPCookieProcessor(cookie_jar))

page_html = opener.open(url).read()

tree = html.fromstring(page_html)

item_names = tree.xpath('//table[//th[text()="Item"]]/tbody/tr/td[1]/a/div//text()')
item_names_versions = []

for i in range(0, len(item_names), 2):
    item_names_versions.append(f'{item_names[i]} ({item_names[i + 1]})')

item_statuses = tree.xpath('//table[//th[text()="Item"]]/tbody/tr/td[7]/text()')

for i, name in enumerate(item_names_versions):
    if re.match(regex, name):
        print(f'{name}\t{item_statuses[i]}')
